<?php
/**
 * @file
 * Code for the Gold - contenu premium feature.
 */

/**
 * Features.
 */
include_once 'gold_premium.features.inc';

/**
 * Permission: view premium content.
 */
const GOLD_PREMIUM_PERM_VIEW = 'view premium content';

/**
 * Implements hook_menu().
 */
function gold_premium_menu() {
  $items = [];

  $items['am-i-premium'] = [
    'title'             => "Am I premium ?",
    'page callback'     => 'gold_premium_page_am_i_premium',
    'access calback'    => 'user_access',                     //
    'access arguments'  => ['access content'],                // -> user_access('access content');
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'gold_premium.pages.inc',
  ];
  $items['am-i-premium/%user'] = [
    'title'             => "Am I premium ?",
    'page callback'     => 'gold_premium_page_am_i_premium',
    'page arguments'    => [1],
    'access arguments'  => ['access content'],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
    'file'              => 'gold_premium.pages.inc',
  ];

  $items['pouet'] = [
    'title'             => "Pouet",
    'page callback'     => 'gold_premium_list_all_nodes',
    'access arguments'  => ['access content'],
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'gold_premium.pages.inc',
  ];

  $items['superform'] = [
    'title'             => "Super formulaire",
    'page callback'     => 'drupal_get_form',
    'page arguments'    => ['gold_premium_mon_form', "Cassoulet"],
    'access arguments'  => ['access content'],
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'gold_premium.pages.inc',
  ];

  $items['admin/people/premium-users'] = [
    'title'             => "Premium users",
    'page callback'     => 'gold_premium_page_premium_users_list',
    'access arguments'  => ['administer users'],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
    'file'              => 'gold_premium.pages.inc',
  ];
  $items['admin/people/premium-users-plus-plus'] = [
    'title'             => "Premium users",
    'page callback'     => 'gold_premium_page_premium_users_list_plus_plus',
    'access arguments'  => ['administer users'],
    'type'              => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
    'file'              => 'gold_premium.pages.inc',
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function gold_premium_permission() {
  return [
    GOLD_PREMIUM_PERM_VIEW => [
      'title'       => t('View premium content'),
      'description' => t('View premium content.'),
    ],
  ];
}

function gold_premium_theme() {
  return [
    'premium_block' => [
      'variables' => ['is_premium' => false, 'account' => null],
      'template'  => 'premium-is-block',
    ],
  ];
}

/**
 * Implements hook_block_info().
 */
function gold_premium_block_info() {
  return [
    'gold_status' => [
      'info'  => t("[GOLD] Current user premium status"),
      'cache' => DRUPAL_NO_CACHE,
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function gold_premium_block_view($delta = '') {
  switch ($delta) {

    case 'gold_status':

      return [
        'content' => [
          '#theme'      => 'premium_block',
          '#account'    => user_load($GLOBALS['user']->uid),
          '#is_premium' => user_access(GOLD_PREMIUM_PERM_VIEW),
        ],
      ];
  }
}

/**
 * Implements hook_form_alter().
 */
function gold_premium_form_alter(&$form, &$form_state, $form_id) {
  // Faire quelques chose
  if ('gold_premium_mon_form' === $form_id) {
    $form['actions']['cancel'] = [
      '#type'   => 'markup',
      '#markup' => l(t("Cancel"), current_path()),
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gold_premium_form_gold_premium_mon_form_alter(&$form, &$form_state) {
  // Faire quelques chose
  $form['actions']['cancel']['#weight'] = -10;
}

/**
 * Implements hook_block_view_alter().
 */
// function gold_premium_block_view_alter(&$data, $block) {
//   if ('gold_premium' === $block->module && 'gold_status' === $block->delta) {
//     $data['content']['#access'] = user_access(GOLD_PREMIUM_PERM_VIEW);
//   }
// }

/**
 * Implements hook_block_view_MODULE_DELTA_alter().
 */
function gold_premium_block_view_gold_premium_gold_status_alter(&$data, $block) {
  $data['content']['#access'] = user_access(GOLD_PREMIUM_PERM_VIEW);
}
