<?php
/**
 * @file
 * Code for the Gold - contenu premium feature.
 */

/**
 * Features.
 */
include_once 'gold_premium.features.inc';

/**
 * Permission: view premium content.
 */
const GOLD_PREMIUM_PERM_VIEW = 'view premium content';

/**
 * Implements hook_permission().
 */
function gold_premium_permission() {
  return [
    GOLD_PREMIUM_PERM_VIEW => [
      'title'       => t('View premium content'),
      'description' => t('View premium content.'),
    ],
  ];
}

function gold_premium_theme() {
  return [
    'premium_block' => [
      'variables' => ['is_premium' => false],
      'template' => 'premium-is-block',
    ],
  ];
}

/**
 * Implements hook_block_info().
 */
function gold_premium_block_info() {
  return [
    'gold_status' => [
      'info'  => t("[GOLD] Current user premium status"),
      'cache' => DRUPAL_NO_CACHE,
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function gold_premium_block_view($delta = '') {
  switch ($delta) {

    case 'gold_status':

      return [
        'content' => [
          '#theme'      => 'premium_block',
          '#is_premium' => user_access(GOLD_PREMIUM_PERM_VIEW),
        ],
      ];
  }
}

/**
 * Implements hook_block_view_alter().
 */
function gold_premium_block_view_alter(&$data, $block) {
  if ('gold_premium' === $block->module && 'gold_status' === $block->delta) {
    $data['content']['#access'] = user_access(GOLD_PREMIUM_PERM_VIEW);
  }
}
